### ISSUE TITLE
GlideApp not found

### ISSUE THREAD

**Issue by programmermager** [qoqa/glide-svg#4]
its only show Glide in import suggestion, not shown GlideApp. i try to use Glide, but the svg image not shown.

**Comment by Kevinrob** [comment]
GlideApp is generated by Glide if you have a GlideModule.  
You can follow the official [documentation](https://bumptech.github.io/glide/doc/generatedapi.html) about this.

This library will add itself to your GlideModule. If you don't have one, the SVG will not work.

Tell me if you need help to configure it.

**Comment by jh0rman** [comment]
How to configure it? pls

**Comment by Kevinrob** [comment]
Hi @jhormanrus! 
As I said, you can follow [the official documentation of Glide](https://bumptech.github.io/glide/doc/generatedapi.html) for configuring `Generated API`.  
After that, you can use it with:

```
GlideApp.with(this)
  .load(url)
  .into(picto_view)
```
