### ISSUE TITLE
setColorFilter doesn't work

### ISSUE THREAD

**Issue by AnthonyFillionMaillet** [qoqa/glide-svg#6]
Your lib works perfectly when I try to load a SVG file into an imageview, thanks!
The only problem I have is that I'm not able to change the tint color.

I tried your sample code:
`it.setColorFilter(Color.BLUE, PorterDuff.Mode.SRC_ATOP)`

But it doesn't work. I'm using Glide 4.9.0.
Any suggestions?

**Comment by AnthonyFillionMaillet** [comment]
Huuum it seems that the problem doesn't come from your lib but probably from recycler view or Glide. When I'm scrolling I can finally see the color tint but at multiple random positions instead of just the one item clicked.

**Comment by AnthonyFillionMaillet** [comment]
Adding `.signature(new ObjectKey(position))` to Glide loading fixed the issue. I think it's because by default all drawables instances loaded from the same resource share a common state.

**Comment by Kevinrob** [comment]
It's possible that Glide optimize and cache the tint with the drawable.
You should probably use something like `.signature(new ObjectKey(url + "#" + position))` 😃
