### ISSUE TITLE
Svg images cannot retain aspect ratio

### ISSUE THREAD

**Issue by GerhardtBruwer** [qoqa/glide-svg#8]
Changing the color works fine, but the image appears very very small in the top left corner of the ImageView. I have no control over the svg file (it has a fixed size). In the SvgBitmapTranscoder class I have tried to svg.documentPreserveAspectRatio = PreserveAspectRatio.STRETCH but it has no effect. Also tried the same in the SvgDecoder class. Chances are that I'm missing something obvious. Any words of advice you can offer me?

**Comment by Kevinrob** [comment]
@GerhardtBruwer Do you have this issue with the last version of the library? `3.0.0`

**Comment by Kevinrob** [comment]
No answer, I close it. Feel free to re-open.
